# SPDX-License-Identifier: GPL-2.0-only
#
# Project: Ecli
# File: sonar-project.properties
# Website: https://www.ecli.io
# Repository: https://github.com/SSobol77/ecli
# PyPI: https://pypi.org/project/ecli-editor/0.0.1/
#
# Copyright (c) 2026 Siergej Sobolewski
#
# Licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for full license text.

sonar.projectKey=ecli-editor-cli
sonar.projectName=ECLI Editor
sonar.projectVersion=1.0
sonar.sources=ecli
sonar.tests=tests
sonar.python.version=3.13.5
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**, **/*.pyc, **/*.pyo, **/*.pyd, **/tests/**/test_*.py
sonar.test.inclusions=**/tests/**, **/tests/**/test_*.py
sonar.test.exclusions=**/tests/**/test_panels.py, **/tests/**/test_git.py, **/tests/**/test_file_browser.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.pylint.reportPath=pylint-report.txt
sonar.python.flake8.reportPath=flake8-report.txt
sonar.python.mypy.reportPath=mypy-report.json
sonar.python.ruff.reportPath=ruff-report.json
sonar.python.pydocstyle.reportPath=pydocstyle-report.txt
sonar.python.bandit.reportPath=bandit-report.json
sonar.python.safety.reportPath=safety-report.json
sonar.python.pydocstyle.enabled=true
sonar.python.pylint.enabled=true
sonar.python.flake8.enabled=true
sonar.python.mypy.enabled=true
sonar.python.ruff.enabled=true
sonar.python.bandit.enabled=true
sonar.python.safety.enabled=true
sonar.python.coverage.enabled=true
sonar.python.pylint.enabled=true
