#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
#
# Project: Ecli
# File: packaging/linux/fpm-common/postinst
# Website: https://www.ecli.io
# Repository: https://github.com/SSobol77/ecli
# PyPI: https://pypi.org/project/ecli-editor/0.0.1/
#
# Copyright (c) 2026 Siergej Sobolewski
#
# Licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for full license text.

# packaging/linux/fpm-common/postinst

set -e

if [ "$1" = "configure" ]; then
    echo "----------------------------------------------------------------------"
    echo "ECLI has been successfully installed."
    echo
    echo "On the first run, user configuration files will be automatically"
    echo "created in the following directory:"
    echo "  ~/.config/ecli/"
    echo
    echo "Please edit the '.env' file in that directory to add your API keys"
    echo "for AI features."
    echo "----------------------------------------------------------------------"
fi

exit 0
