# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pipx install uv

      - name: Sync deps
        run: uv sync --frozen

      - name: Lint (ruff)
        run: uv run ruff check src tests

      - name: Format check (ruff)
        run: uv run ruff format --check src tests

      - name: Pytest with coverage
        run: uv run pytest --cov -q

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=ecli
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.python.version=3.11
            -Dsonar.python.coverage.reportPaths=coverage.xml
