name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pipx install uv

      - name: Sync deps
        run: uv sync --frozen

      - name: Lint (ruff)
        run: uv run ruff check src tests

      - name: Format check (ruff)
        run: uv run ruff format --check src tests

      - name: Pytest
        run: uv run pytest -q
